### ISSUE TITLE
Scoreboard score is not removed on 1.7

### ISSUE THREAD

**Issue by ItsHarry** [sillerud/BungeeCord#10]
Hey there

I have found a problem that is specific to 1.7 clients:

``` java
objective.getScore(Bukkit.getOfflinePlayer(ChatColor.GREEN + "Round " + roundNumber)).setScore(-1);
scoreboard.resetScores(Bukkit.getOfflinePlayer(ChatColor.GREEN + "Round " + roundNumber));
```

In this case, the score is not removed from the Scoreboard.

Any ideas?

**Comment by sillerud** [comment]
This is a bit tricky, 1.6 uses a byte, where the value 0 is update or create, and 1 is remove, while 1.7 uses 0 for creating, 1 for removing and 2 for updating, and i don't really know what updating without creating it would do, so I would either have to add more code then just a packet rewrite, or modify the server itself. Can you come to the IRC channel when you see this?
