### ISSUE TITLE
Add Multiserver Version Support?

### ISSUE THREAD

**Issue by Paulomart** [sillerud/BungeeCord#14]
It would be very cool, if you could add a way to have 1.7 and 1.6 Servers in your Bungee. Players could only connect so Servers that have a lower Protocol Version has they have.

**Comment by literalplus** [comment]
This change would overcomplicate stuff in my opinion. Also, the current implementation accepts only 1.6 packets, so there would have to be lots of more checks. 
(edited because I overread the last line - It's 4 am)
-- This message was sent from my tablet. Check my homepage!

**Comment by Paulomart** [comment]
I thought that. But this way there is no way to have 1.7.x things on a Server..

**Comment by literalplus** [comment]
Well, I think you have to choose between 1.7 items and keeping 1.6 users :)
(But I reckon that people should have switched to 1.7 by now; Maybe make a
plugin that checks on join what version the user is on. When you have that
data, it might be easier for you to decide)

--xxyy [ xxyy98@gmail.com -
http://xxyy.nowak-at.net/http://lnk.nowak-at.net/?l=web-xy-ref-mail-
@_xxyy http://lnk.nowak-at.net/?l=twitter-ref-mail]
wow such impress.
There are 10 types of people in the world. Those who understand base 3,
those who don't and those who still think this is a binary joke.

2014/1/3 Paulomart notifications@github.com
