### ISSUE TITLE
Add Support For PreLoginEvent

### ISSUE THREAD

**Issue by Katelyn-SN** [sillerud/BungeeCord#21]

**Comment by literalplus** [comment]
To get this, you could
- Add a description
- Make a PR

(Yes, I mean _both_)

**Comment by Katelyn-SN** [comment]
I tried merging PreLoginEvent commit into the source with no success no need for a pull request when I have nothing to commit. This is here for someone to try and add it this event is required for bungee plugin like NeverDownProxy

**Comment by literalplus** [comment]
@tf101-wizard I opened a PR proposing the changes you asked for. Please test the provided artifacts and confirm that they work as intended.
